name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - run: pip install requests

      - name: Run script
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: python main.py

      - name: Save seen items
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add seen.json || true
          git diff --cached --quiet || git commit -m "update seen items"
          git push
