name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"

permissions:
  contents: write

jobs:
  post-clothing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GROUP_ID: "15938842"
        run: node index.js

      - name: Commit seen file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add seen.json
          git diff --cached --quiet || git commit -m "Update seen items"
          git push
